#!/bin/bash

node ../s16a/s16a --asm asm/sys16.s16a --out asm/sys16.s16o

echo -en "\n";

if [ "$#" -ne 1 ]; then
    ENDIANESS='little-endian';
else
    ENDIANESS=$1;
fi

node ../s16l/s16l asm/sys16.s16o --out exe/sys16 --byte-order $ENDIANESS
